# These are supported funding model platforms

github: losolio
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
buy_me_a_coffee: losol
