name: Docker Image CI

on:
  push:
    branches: [master]
    tags:
    - v*
  pull_request:
    branches: [master] 

env:
  ORGANIZATION_NAME: losolio
  IMAGE_NAME: converto

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          echo ${{ date "+%Y-%m-%d-%H:%M" }}
          echo ${{ GITHUB_RUN_NUMBER }}
          echo ${{ date "+%Y-%m-%d" + "." + GITHUB_RUN_NUMBER }}
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  push:
    name: Build image and push to Docker Hub.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.ORGANIZATION_NAME }}/${{ env.IMAGE_NAME }}
          tag_with_ref: true
          tags: latest
